import Navigation from "./navigation";
import Headshot from "./headshot";
import Footer from "./footer";
import Image from "next/image";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quattro = localFont({
  src: [
    {
      path: "../fonts/iAWriterQuattroS-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/iAWriterQuattroS-Italic.woff2",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/iAWriterQuattroS-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/iAWriterQuattroS-BoldItalic.woff2",
      weight: "700",
      style: "italic",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body
        className={`${quattro.className} antialiased flex h-full flex-col`}
      >
        <div className="fixed inset-0 flex justify-center sm:px-8">
          <div className="flex w-full max-w-7xl lg:px-8">
            <div className="w-full ring-1 bg-zinc-900 ring-zinc-300/20">
            </div>
          </div>
        </div>

        <div className="relative">
          <div className="sticky backdrop-blur z-50 top-0 h-20 sm:w-[90%] md:w-[90%] lg:w-[85%] max-w-[68rem] mx-auto">
            <div className="flex items-center justify-between sm:justify-start md:justify-center h-full max-w-5xl mx-auto">
              <Headshot/>
              <Navigation/>
                <div className="mx-auto min-w-32">
                  <button className="group rounded-full bg-white/90 px-3 py-1.5 shadow-lg shadow-zinc-800/5 ring-1 ring-zinc-900/5 backdrop-blur transition dark:bg-zinc-800/90 dark:ring-white/10 dark:hover:ring-white/20">
                    <Image  className="" alt="bisected circle" src="/theme.svg" width={30} height={30}/>
                  </button>
                </div>
            </div>
          </div>

          {children}
          <Footer/>
        </div>

      </body>
    </html>
  );
}
